version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "5173:5173"
    environment:
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
      - VITE_API_URL=${VITE_API_URL}
    volumes:
      - ./src:/app/src
    command: npm run dev -- --host 0.0.0.0